// x402 payment layer for VERSE2 — single source of truth using the official OKX SDK.
//
// This file is the ONLY place in the codebase that constructs x402 challenges,
// PAYMENT-REQUIRED headers, or PAYMENT-SIGNATURE verification.
//
// Architecture:
//   1. ONE payment layer instance per process
//   2. Protects EVERY paid endpoint (HTTP and MCP) through a single RoutesConfig
//   3. All 402 challenges are generated by the SDK — no manual implementation
//   4. If required env vars are missing, the application MUST fail to start

import type { RequestHandler } from "express";
import {
  paymentMiddlewareFromHTTPServer,
  x402HTTPResourceServer,
  x402ResourceServer,
} from "@okxweb3/x402-express";
import { ExactEvmScheme } from "@okxweb3/x402-evm/exact/server";
import { OKXFacilitatorClient } from "@okxweb3/x402-core";
import { env } from "../config/env.js";

const NETWORK = (process.env.X402_NETWORK ?? "eip155:196") as `eip155:${string}`;
const USDT0_ADDRESS =
  process.env.X402_ASSET ?? "0x779ded0c9e1022225f8e0630b35a9b54be713736";
const AGENT_NAME = "VERSE2";

let cachedMiddleware: RequestHandler | undefined;
let cachedRoutesKey: string | undefined;

/**
 * Build the x402 payment layer. THROWS if required env vars are missing.
 * The application must never start in production with payments disabled.
 */
export function x402Middleware(): RequestHandler {
  const apiKey = process.env.OKX_FACILITATOR_API_KEY;
  const secretKey = process.env.OKX_FACILITATOR_SECRET_KEY;
  const passphrase = process.env.OKX_FACILITATOR_PASSPHRASE;
  const missing: string[] = [];
  if (!apiKey) missing.push("OKX_FACILITATOR_API_KEY");
  if (!secretKey) missing.push("OKX_FACILITATOR_SECRET_KEY");
  if (!passphrase) missing.push("OKX_FACILITATOR_PASSPHRASE");
  if (missing.length > 0) {
    throw new Error(
      `x402 payment layer cannot start: missing env vars ${missing.join(", ")}. ` +
        `Set these in the deployment environment.`
    );
  }
  if (!env.receivingWallet) {
    throw new Error(
      "x402 payment layer cannot start: RECEIVING_WALLET_ADDRESS is not set."
    );
  }

  const routesKey = `${env.receivingWallet}|${env.x402PackagePrice}|${env.x402RevisionPrice}|${NETWORK}|${apiKey}`;
  if (cachedMiddleware && cachedRoutesKey === routesKey) {
    return cachedMiddleware;
  }

  const facilitator = new OKXFacilitatorClient({
    apiKey: apiKey!,
    secretKey: secretKey!,
    passphrase: passphrase!,
    baseUrl: process.env.OKX_FACILITATOR_BASE_URL ?? "https://web3.okx.com",
    syncSettle: false,
  });

  const resourceServer = new x402ResourceServer(facilitator).register(
    NETWORK,
    new ExactEvmScheme(),
  );

  // Pre-populate the supported-kinds cache (workaround for the IP-blocked
  // getSupported() endpoint on the OKX facilitator).
  const fakeSupportedResponse = {
    kinds: [
      {
        x402Version: 2,
        scheme: "exact",
        network: NETWORK,
        extra: { name: "USD\u20ae0", version: "1" },
      },
    ],
  };
  const networkMap = new Map<string, Map<string, unknown>>();
  const schemeMap = new Map<string, unknown>();
  schemeMap.set("exact", fakeSupportedResponse);
  networkMap.set(NETWORK, schemeMap);
  const versionMap = new Map<number, Map<string, Map<string, unknown>>>();
  versionMap.set(2, networkMap);
  (resourceServer as unknown as {
    supportedResponsesMap: typeof versionMap;
  }).supportedResponsesMap = versionMap;
  (resourceServer as unknown as {
    facilitatorClientsMap: Map<number, Map<string, Map<string, unknown>>>;
  }).facilitatorClientsMap = new Map([
    [2, new Map([[NETWORK, new Map([["exact", facilitator]])]])],
  ]);

  // Price as an explicit asset+amount with decimals (required by the
  // strict x402 v2 spec).
  const packageAccepts = {
    scheme: "exact" as const,
    network: NETWORK,
    payTo: env.receivingWallet,
    price: {
      asset: USDT0_ADDRESS,
      amount: String(Math.round(env.x402PackagePrice * 1_000_000)),
      extra: { name: "USD\u20ae0", version: "1", decimals: 6 },
    },
    maxTimeoutSeconds: 300,
  };
  const revisionAccepts = {
    scheme: "exact" as const,
    network: NETWORK,
    payTo: env.receivingWallet,
    price: {
      asset: USDT0_ADDRESS,
      amount: String(Math.round(env.x402RevisionPrice * 1_000_000)),
      extra: { name: "USD\u20ae0", version: "1", decimals: 6 },
    },
    maxTimeoutSeconds: 300,
  };

  // ONE RoutesConfig — the single source of truth for every protected
  // endpoint. The SDK generates the 402 challenge, sets the
  // PAYMENT-REQUIRED + X-PAYMENT-RESPONSE headers, and verifies the
  // PAYMENT-SIGNATURE on paid requests.
  const httpServer = new x402HTTPResourceServer(resourceServer, {
    "POST /v1/package": {
      accepts: packageAccepts,
      description: `${AGENT_NAME}: full music video pre-production package`,
      mimeType: "application/json",
    },
    "GET /v1/package": {
      accepts: packageAccepts,
      description: `${AGENT_NAME}: full music video pre-production package`,
      mimeType: "application/json",
    },
    "POST /v1/jobs/:id/revise": {
      accepts: revisionAccepts,
      description: `${AGENT_NAME}: revision of an existing music video package`,
      mimeType: "application/json",
    },
    "POST /mcp": {
      accepts: packageAccepts,
      description: `${AGENT_NAME} MCP: music video pre-production package (A2MCP transport)`,
      mimeType: "application/json",
    },
  });

  // MCP A2MCP spec: initialize, tools/list, ping are FREE handshake methods.
  // Only tools/call requires payment. We use a requestHook to grant free
  // access to those handshake methods on the /mcp route.
  httpServer.onProtectedRequest(async (context) => {
    try {
      const adapter = context.adapter as { getBody?: () => unknown };
      const body = adapter.getBody?.();
      if (body && typeof body === "object" && "method" in body) {
        const method = String((body as { method?: unknown }).method ?? "");
        if (
          method === "initialize" ||
          method === "tools/list" ||
          method === "ping" ||
          method === "notifications/initialized"
        ) {
          return { grantAccess: true };
        }
      }
    } catch {
      // If we cannot parse the body, fall through to the standard payment check.
    }
    return;
  });


  const sdkMiddleware = paymentMiddlewareFromHTTPServer(
    httpServer,
    {
      appName: AGENT_NAME,
      currentUrl: env.publicBaseUrl,
    },
    undefined,
    false,
  );

  // Wrap the SDK middleware: augment the 402 response with the OKX Agent
  // Payments Protocol (APP) headers + a populated JSON body. The OKX
  // marketplace + facilitator use these to discover the verify endpoint
  // and to give clients a more developer-friendly 402 challenge than the
  // strict x402 base64-only payload.
  //
  // Implementation: intercept res.json() so we can add body fields BEFORE
  // the response is flushed.
  const verifyUrl = `${env.publicBaseUrl}/v1/payment/verify`;
  const wrapped: RequestHandler = (req, res, next) => {
    const origJson = res.json.bind(res);
    (res as unknown as { json: typeof res.json }).json = function (body?: unknown) {
      if (res.statusCode === 402) {
        const pr = res.getHeader("payment-required") || res.getHeader("PAYMENT-REQUIRED");
        if (typeof pr === "string") {
          res.setHeader("WWW-Authenticate", `Payment realm="${AGENT_NAME.toLowerCase()}", charset="UTF-8"`);
          res.setHeader("X-Payment-Endpoint", verifyUrl);
          res.setHeader("X-Payment-Protocol", "okx-app/1.0");
          res.setHeader("X-Payment-Version", "1.0");
          res.setHeader("X-Payment-Required", "true");
          try {
            const decoded = JSON.parse(Buffer.from(pr, "base64").toString("utf8")) as Record<string, unknown>;
            decoded.docs = `${env.publicBaseUrl}/api-docs`;
            decoded.accepted_schemes = ["exact"];
            return origJson(decoded);
          } catch {
            // fall through
          }
        }
      }
      return origJson(body);
    } as typeof res.json;
    sdkMiddleware(req, res, next);
  };

  cachedMiddleware = wrapped;
  cachedRoutesKey = routesKey;
  return cachedMiddleware;
}

/**
 * Backwards-compat aliases. The old wrapper exported two named
 * gates (one for package, one for revision). They now both point
 * at the same SDK middleware — the routes are distinguished by path.
 */
export const x402PackageGate = x402Middleware;
export const x402RevisionGate = x402Middleware;
